module.exports = (sequelize, DataTypes) => sequelize.define('SecurityPolicies', {
  security_policy_id: { type: DataTypes.BIGINT.UNSIGNED, primaryKey: true, autoIncrement: true },
  tenant_uuid: { type: DataTypes.STRING(36), allowNull: false },
  policy_version: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false },
  min_password_length: { type: DataTypes.TINYINT.UNSIGNED, allowNull: false },
  require_uppercase: { type: DataTypes.BOOLEAN, allowNull: false },
  require_lowercase: { type: DataTypes.BOOLEAN, allowNull: false },
  require_number: { type: DataTypes.BOOLEAN, allowNull: false },
  require_special_character: { type: DataTypes.BOOLEAN, allowNull: false },
  password_history_count: { type: DataTypes.TINYINT.UNSIGNED, allowNull: false },
  password_max_age_days: { type: DataTypes.SMALLINT.UNSIGNED, allowNull: true },
  max_failed_attempts: { type: DataTypes.TINYINT.UNSIGNED, allowNull: false },
  lockout_duration_minutes: { type: DataTypes.SMALLINT.UNSIGNED, allowNull: false },
  access_token_lifetime_minutes: { type: DataTypes.SMALLINT.UNSIGNED, allowNull: false },
  refresh_token_lifetime_days: { type: DataTypes.SMALLINT.UNSIGNED, allowNull: false },
  max_session_duration_minutes: { type: DataTypes.SMALLINT.UNSIGNED, allowNull: false },
  max_concurrent_sessions: { type: DataTypes.TINYINT.UNSIGNED, allowNull: true },
  mfa_required: { type: DataTypes.BOOLEAN, allowNull: false },
  status: { type: DataTypes.STRING(30), allowNull: false },
  effective_from: { type: DataTypes.DATE, allowNull: false },
  effective_to: { type: DataTypes.DATE, allowNull: true },
  created_by: { type: DataTypes.BIGINT, allowNull: true },
  created_on: { type: DataTypes.DATE, allowNull: false },
  modified_by: { type: DataTypes.BIGINT, allowNull: true },
  modified_on: { type: DataTypes.DATE, allowNull: false }
}, { tableName: 'security_policies', timestamps: false, freezeTableName: true });
